import { Dayjs } from "dayjs";
import { CustomerRequisite } from "./CustomerRequisite";

export type Customer = {
  id: number;
  pin: string;
  okpo: string;
  postalCode: string;
  ugns: string;
  regNumber: string;
  organizationTypeId: number;
  name: string;
  address: string;
  director: string;
  nomer: string;
  phone1: string;
  lastName?: string;
  firstName?: string;
  secondName?: string;
  phone2: string;
  email: string;
  email_2?: string;
  isForeign?: boolean;
  isPhysical?: boolean;
  identity_document_type_code?: string;
  foreignCountry?: number;
  allowNotification?: boolean;
  bank?: string;
  bik?: string;
  payment_account?: string;
  passport_series?: string;
  passport_issued_date?: Dayjs;
  passport_whom_issued?: string;
};

export type CustomerCreateModel = {
  id: number;
  pin: string;
  okpo: string;
  postalCode: string;
  ugns: string;
  regNumber: string;
  organizationTypeId: number;
  name: string;
  address: string;
  director: string;
  nomer: string;
  phone1: string;
  phone2: string;
  email: string;
  email_2?: string;
  isForeign?: boolean;
  isPhysical?: boolean;
  identity_document_type_code?: string;
  identity_document_type_id?: number;
  foreignCountry?: number;
  requisits: CustomerRequisite[];
  allowNotification?: boolean;
  passport_series?: string;
  passport_issued_date?: Dayjs;
  passport_whom_issued?: string;
  lastName?: string | null;
  firstName?: string | null;
  secondName?: string | null;
};
